osmfj/sotmjp-website

.travis.yml

just testing flake8

---

fixtures/boxes.json

add missing fixtures for box definitions

---

sotmjp/templates/homepage.html
sotmjp/templates/responsive_base.html
sotmjp/templates/site_base.html

update headline title as long version

---

utils/guidebook_csv.py

update guidebook data script

---

misc/init-gunicorn.conf

introduce gunicorn starter script

---

sotmjp/templates/homepage.html
sotmjp/templates/site_base.html

drop csis logo and update title line

---

sotmjp/proposals/admin.py

fix proposals model error

---

sotmjp/profile/__init__.py
sotmjp/profile/apps.py
sotmjp/proposals/forms.py
sotmjp/templates/proposals/proposal_edit.html
sotmjp/templates/proposals/proposal_submit_kind.html
sotmjp/templates/site_base.html
sotmjp/urls.py
sotmjp/views.py

Issue cfp show

---

misc/nginx/production.conf
misc/nginx/staging.conf

update nginx config sample

---

requirements/project.txt
sotmjp/templates/site_base.html

interim fix for #50

---

sotmjp/proposals/models.py

- hack for #47
- it should be configurable as model.

update talk time frame

---

sotmjp/settings/base.py

Reflect change
https://github.com/miurahr/symposion/commit/f6597d032124da67b42607b00426769fac5c897c

import symposion locale files

---

requirements/project.txt

fix version

---

sotmjp/templates/site_base.html

フッターが二回出てしまってるので、
pinax_theme_bootstrapで表示だけするようにblockだけ定義するようにした。

show footer only once

---

requirements/project.txt
sotmjp/settings/base.py

drop admin_tools

---

fixtures/proposals.json
sotmjp/templates/dashboard.html

skip proposal kind selection when submission

---

sotmjp/proposals/forms.py
sotmjp/settings/base.py

remove profile from INSTALLED_APP

---

sotmjp/settings/base.py
sotmjp/templates/admin/base_site.html
sotmjp/templatetags/admin_reorder_tag.py

admin index reorder

---

sotmjp/templates/homepage.html
sotmjp/templates/pinax/blog/blog_post.html

fix blog post display

---

sotmjp/templates/proposals/_proposal_fields.html
sotmjp/templates/proposals/proposal_detail.html

fixed #102

---

sotmjp/templates/proposals/proposal_detail.html

fixed #104

---

sotmjp/static/less/site.less
sotmjp/templates/schedule/_grid.html

Two color schedule grid

---

sotmjp/templates/schedule/_grid.html
sotmjp/templates/schedule/presentation_detail.html

fix grid content_override and cleanup detail

---

sotmjp/templates/homepage.html

use jquery attr function instead of data function.

sponser logos in top page is not show with retian display
